### ISSUE TITLE
Possible bug in Hann wavelet implementation (without warping)

### ISSUE THREAD

**Issue by nshervt** [alelab-upenn/graph-scattering-transforms#3]
In the definition of the Hann kernel, 'm a' (as appears in eq(4) from [Shuman et. al.](https://ieeexplore.ieee.org/abstract/document/7088640) and defined in eq. (10)) is defined as

https://github.com/alelab-upenn/graph-scattering-transforms/blob/c8d3183e81964614a87f2989bb01aceb26eba2a2/Modules/graphScattering.py#L212

Later on, for the case without warping you define

https://github.com/alelab-upenn/graph-scattering-transforms/blob/c8d3183e81964614a87f2989bb01aceb26eba2a2/Modules/graphScattering.py#L230

This doesn't seem right. Let's say `J = 3`, then `t` has size `(3,)`. Then you call `t[3]`, which is out of bound for `t` with size `(3,)`.

**Comment by fgfgama** [comment]
Hi, nshervt! Thank you very much for pointing this out.

You're correct, line 230 should be replaced by
`psi =  HannKernel(e - t[J-1], J, R, eMax)`

This has been replaced in the updated version.

Thanks!
